if(JEMALLOC_PATH)	
	find_path(JEMALLOC_INCLUDE_DIRS NAMES "jemalloc/jemalloc.h" PATHS ${JEMALLOC_PATH})
	if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
		find_library(JEMALLOC_LIBRARIES NAMES "jemallocd.lib" "libjemalloc.a" PATHS ${JEMALLOC_PATH})
	else()
		find_library(JEMALLOC_LIBRARIES NAMES "jemalloc.lib" "libjemalloc.a" PATHS ${JEMALLOC_PATH})
	endif()
else()
	find_path(JEMALLOC_INCLUDE_DIRS NAMES "jemalloc/jemalloc.h")
	if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
		find_library(JEMALLOC_LIBRARIES NAMES "jemallocd.lib" "libjemalloc.a")
	else()
		find_library(JEMALLOC_LIBRARIES NAMES "jemalloc.lib" "libjemalloc.a")
	endif()
endif()
if(JEMALLOC_INCLUDE_DIRS)
	if(JEMALLOC_LIBRARIES)
		set(JEMALLOC_FOUND)
		message(STATUS "--Found Jemalloc Library ${JEMALLOC_LIBRARIES}")
		message(STATUS "--Found Jemalloc Include ${JEMALLOC_INCLUDE_DIRS}")
	endif()
endif()